Landing Page
ubc-biztech/bt-web pull request #195
Opened 2020-12-13 07:40 UTC by pzhang24

🎟️ Ticket(s): Closes #181

👷 Changes: A brief summary of what changes were introduced.

- Create Landing Page for Min VP 
- Modify router to display Landing Page component when user visits '/' (unless user is currently logged in as admin)
- Refactor icon bar (FB, IG, LinkedIn, etc) into separate Component for reuse throughout app

💭 Notes: Any additional things to take into consideration.
- Not sure how login is going to work for admins... didn't do anything about that in this PR

Wait! Before you merge, have you checked the following:

📷 Screenshots
![image](https://user-images.githubusercontent.com/55124377/102006040-96754a80-3cd2-11eb-9038-b8e5b4872f36.png)
![image](https://user-images.githubusercontent.com/55124377/102006052-c0c70800-3cd2-11eb-9e83-fdbf30f6403a.png)
![image](https://user-images.githubusercontent.com/55124377/102006094-3337e800-3cd3-11eb-9b07-0a345e12be8e.png)

(prefer animated gif)

## Checklist
- [x] Looks good on large screens
- [x] Looks good on mobile

2020-12-13 08:07 UTC, pzhang24 commented
Found some problems where the images and the bottom text/iconbar wasn't centered properly on mobile view. Should be fixed now.
Note: the icons themselves aren't perfectly centered (since I borrowed them from the registration page footer)
![image](https://user-images.githubusercontent.com/55124377/102006513-7f385c00-3cd6-11eb-82cc-849f5a74cb2e.png)
![image](https://user-images.githubusercontent.com/55124377/102006558-e6eea700-3cd6-11eb-9f75-7273513e12a8.png)

2020-12-14 03:41 UTC, dchen150 approved these changes

2020-12-14 03:43 UTC, dchen150 requested changes
the logos don't look like they're centered under the bottom line - is that just me?

2020-12-14 23:52 UTC, pzhang24 commented
Good catch - the icons should be centered now below the line.

2020-12-15 04:23 UTC, dchen150 approved these changes

2020-12-15 04:23 UTC, merged